// Generated by view binder compiler. Do not edit!
package com.example.myapplication.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.Toolbar;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.myapplication.R;
import de.hdodenhof.circleimageview.CircleImageView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityChatBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView active;

  @NonNull
  public final ImageView attachment;

  @NonNull
  public final ImageView camera;

  @NonNull
  public final TextView chatname;

  @NonNull
  public final CircleImageView imageView2;

  @NonNull
  public final LinearLayout main;

  @NonNull
  public final EditText messageBox;

  @NonNull
  public final RecyclerView recyclerview;

  @NonNull
  public final ImageView sendbutton;

  @NonNull
  public final Toolbar toolbar;

  private ActivityChatBinding(@NonNull LinearLayout rootView, @NonNull TextView active,
      @NonNull ImageView attachment, @NonNull ImageView camera, @NonNull TextView chatname,
      @NonNull CircleImageView imageView2, @NonNull LinearLayout main, @NonNull EditText messageBox,
      @NonNull RecyclerView recyclerview, @NonNull ImageView sendbutton, @NonNull Toolbar toolbar) {
    this.rootView = rootView;
    this.active = active;
    this.attachment = attachment;
    this.camera = camera;
    this.chatname = chatname;
    this.imageView2 = imageView2;
    this.main = main;
    this.messageBox = messageBox;
    this.recyclerview = recyclerview;
    this.sendbutton = sendbutton;
    this.toolbar = toolbar;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityChatBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityChatBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_chat, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityChatBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.active;
      TextView active = ViewBindings.findChildViewById(rootView, id);
      if (active == null) {
        break missingId;
      }

      id = R.id.attachment;
      ImageView attachment = ViewBindings.findChildViewById(rootView, id);
      if (attachment == null) {
        break missingId;
      }

      id = R.id.camera;
      ImageView camera = ViewBindings.findChildViewById(rootView, id);
      if (camera == null) {
        break missingId;
      }

      id = R.id.chatname;
      TextView chatname = ViewBindings.findChildViewById(rootView, id);
      if (chatname == null) {
        break missingId;
      }

      id = R.id.imageView2;
      CircleImageView imageView2 = ViewBindings.findChildViewById(rootView, id);
      if (imageView2 == null) {
        break missingId;
      }

      LinearLayout main = (LinearLayout) rootView;

      id = R.id.messageBox;
      EditText messageBox = ViewBindings.findChildViewById(rootView, id);
      if (messageBox == null) {
        break missingId;
      }

      id = R.id.recyclerview;
      RecyclerView recyclerview = ViewBindings.findChildViewById(rootView, id);
      if (recyclerview == null) {
        break missingId;
      }

      id = R.id.sendbutton;
      ImageView sendbutton = ViewBindings.findChildViewById(rootView, id);
      if (sendbutton == null) {
        break missingId;
      }

      id = R.id.toolbar;
      Toolbar toolbar = ViewBindings.findChildViewById(rootView, id);
      if (toolbar == null) {
        break missingId;
      }

      return new ActivityChatBinding((LinearLayout) rootView, active, attachment, camera, chatname,
          imageView2, main, messageBox, recyclerview, sendbutton, toolbar);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
