// Generated by view binder compiler. Do not edit!
package com.example.myapplication.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.myapplication.R;
import de.hdodenhof.circleimageview.CircleImageView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityCreditScoreBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView contact;

  @NonNull
  public final Button gotochat;

  @NonNull
  public final TextView last;

  @NonNull
  public final LinearLayout main;

  @NonNull
  public final CircleImageView profile;

  @NonNull
  public final TextView score;

  private ActivityCreditScoreBinding(@NonNull LinearLayout rootView, @NonNull TextView contact,
      @NonNull Button gotochat, @NonNull TextView last, @NonNull LinearLayout main,
      @NonNull CircleImageView profile, @NonNull TextView score) {
    this.rootView = rootView;
    this.contact = contact;
    this.gotochat = gotochat;
    this.last = last;
    this.main = main;
    this.profile = profile;
    this.score = score;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityCreditScoreBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityCreditScoreBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_credit_score, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityCreditScoreBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.contact;
      TextView contact = ViewBindings.findChildViewById(rootView, id);
      if (contact == null) {
        break missingId;
      }

      id = R.id.gotochat;
      Button gotochat = ViewBindings.findChildViewById(rootView, id);
      if (gotochat == null) {
        break missingId;
      }

      id = R.id.last;
      TextView last = ViewBindings.findChildViewById(rootView, id);
      if (last == null) {
        break missingId;
      }

      LinearLayout main = (LinearLayout) rootView;

      id = R.id.profile;
      CircleImageView profile = ViewBindings.findChildViewById(rootView, id);
      if (profile == null) {
        break missingId;
      }

      id = R.id.score;
      TextView score = ViewBindings.findChildViewById(rootView, id);
      if (score == null) {
        break missingId;
      }

      return new ActivityCreditScoreBinding((LinearLayout) rootView, contact, gotochat, last, main,
          profile, score);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
